# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - master
      
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |            
            ls
            cd src
            ls
            cd ../


      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run: npm install

      # - save_cache:
      #     key: v1-dependencies-{{ checksum "package.json" }}
      #     paths:
      #       - node_modules
      
    # - run:
    #     command: npm run test

      # - run:
      #     command: npm run build 

      - add_ssh_keys:
          fingerprints:
            - "14:9e:b9:4a:9d:3e:10:b2:15:8b:b4:2c:6f:ff:80:27"

      - run:
          command: |
            ls
            cd src
            ls
            cd pages 
            ls
            ssh-keyscan checkpointlive.com >> ~/.ssh/known_hosts
            scp "*.*" ${USER}@${DOMAIN}:/${DIR_PATH}/
 

# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
            
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master

